#!/bin/sh
#
# Start a timer in the background

if [ $# -le 1 ]; then
  echo "Insuficient input paramteters"
  exit 1
fi
if ! [ -f $2 ]; then
  echo "Missing info file"
  exit 2
fi

profile=$1

sed -i "s/^current .*\$/current $profile/" $2
sed -i "s/^start .*\$/start $(date +%s)/" $2
