#!/bin/sh

remaining() {
  if [ -e $statusfile ]; then
    stime=$(cat $statusfile | awk '/start/ {print $2}')
    time=$(cat $configfile | awk '/'$(current)' / {print $2}')
    echo $(($stime - $(date +%s) + $time))
  fi
}

current() {
  if ! [ -e $statusfile ]; then
    echo "null"
  else
    cat $statusfile | awk '/current/ {print $2}'
  fi
}

next() {
  cat $configfile | awk '/'$(current)' / {print $3}'
}

update() {
  printf "current %s\nstart %s" $1 $(date +%s) > $statusfile
}

list() {
  cat $configfile | awk '{print $1}'
}

s=0
k=0
g=0
configdir="$HOME/.config/pomodoro"
configfile="$configdir/config"
statusfile="$HOME/.pomodoro"

if ! [ -e $configfile ]; then
  mkdir -p $configdir
  cp /usr/share/doc/pomodoro/config.def $configfile
fi

if [ $# -le 0 ]; then 
  selection=$(printf "start\nkill" | dmenu)
  if [ $? -ne 0 ]; then
    exit
  fi
  if [ "$selection" = "start" ]; then
    s=1
  else
    k=1
  fi
fi

while getopts ":sgk" opt; do
  case $opt in
    s)
      s=1
      ;;
    k)
      k=1
      ;;
    g)
      g=1
      ;;
    \?)
      exit 1
  esac
done

if [ $s = 1 ]; then
  if [ $# -le 1 ]; then
    profile=$(list | dmenu)
    if [ $? -ne 0 ]; then
      exit
    fi
  else
    profile=$2
  fi
  update $profile
fi

if [ $k = 1 ]; then
  rm $statusfile
fi

if [ $g = 1 ]; then
  if [ "$(current)" = "null" ]; then
    exit 1
  else
    if [ $(remaining) -le 0 ]; then
      notify-send "Timer $(current)" "done"
      update $(next)
      pomodoro -g
    else
      echo $(printf "%s %02d:%02d" $(current) $(($(remaining) / 60)) $(($(remaining) % 60)))
    fi
  fi
fi
