#!/bin/sh

remaining() {
  stime=$(cat $infofile | awk '/start/ {print $2}')
  time=$(cat $infofile | awk '/'$(current)' / {print $2}')
  echo $(( $time - $(date +%s) + $stime ))
}

current() {
  cat $infofile | awk '/current/ {print $2}'
}

next() {
  cat $infofile | awk '/'$(current)' / {print $3}'
}

update() {
  sed -i "s/^current .*\$/current $1/" $infofile
  sed -i "s/^start .*\$/start $2/" $infofile
}

list() {
  cat $infofile | awk '/#profiles/{flag=1;next}flag{print $1}'
}

s=0 #Start
k=0 #Kil
g=0 #Get time
infodir="$HOME/.config/pomodoro"
infofile="$infodir/config"

# Check if the info file exists.
if ! [ -e $infofile ]; then
  mkdir -p $infodir
  cp /usr/share/doc/pomodoro/config.def $infofile
fi

# If no parameters, show dmenu.
if [ $# -le 0 ]; then 
  selection=$(printf "start\nkill" | dmenu)
  if [ $? -ne 0 ]; then
    exit
  fi
  if [ "$selection" = "start" ]; then
    s=1
  fi
  if [ "$selection"  = "kill" ]; then
    k=1
  fi
fi

while getopts ":sgk" opt; do
  case $opt in
    s)
      s=1
      ;;
    k)
      k=1
      ;;
    g)
      g=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
  esac
done

if [ $s = 1 ]; then
  if [ $# -le 1 ]; then
    profile=$(list | dmenu)
    if [ $? -ne 0 ]; then
      exit
    fi
  else
    profile=$2
  fi

  update $profile $(date +%s)
fi

if [ $k = 1 ]; then
  update null 0
fi

if [ $g = 1 ]; then
  if [ $(current) = "null" ]; then
    exit 1
  fi

  if [ $(remaining) -le 0 ]; then
    notify-send "Timer $(current)" "done"
    update $(next) $(date +%s)
    pomodoro -g
  else
    t=$(printf "%02d:%02d" $(( $(remaining) / 60 )) $(( $(remaining) % 60 )))
    echo "$(current) $t"
  fi
fi
